package com.koperasi.bean;
// Generated Dec 23, 2016 4:28:22 PM by Hibernate Tools 4.3.1



/**
 * Barang generated by hbm2java
 */
public class Barang  implements java.io.Serializable {


     private String kdBarang;
     private String namaBarang;
     private Long harga;
     private String jumlah;

    public Barang() {
    }

	
    public Barang(String kdBarang) {
        this.kdBarang = kdBarang;
    }
    public Barang(String kdBarang, String namaBarang, Long harga, String jumlah) {
       this.kdBarang = kdBarang;
       this.namaBarang = namaBarang;
       this.harga = harga;
       this.jumlah = jumlah;
    }
   
    public String getKdBarang() {
        return this.kdBarang;
    }
    
    public void setKdBarang(String kdBarang) {
        this.kdBarang = kdBarang;
    }
    public String getNamaBarang() {
        return this.namaBarang;
    }
    
    public void setNamaBarang(String namaBarang) {
        this.namaBarang = namaBarang;
    }
    public Long getHarga() {
        return this.harga;
    }
    
    public void setHarga(Long harga) {
        this.harga = harga;
    }
    public String getJumlah() {
        return this.jumlah;
    }
    
    public void setJumlah(String jumlah) {
        this.jumlah = jumlah;
    }




}


