package com.koperasi.bean;
// Generated Dec 23, 2016 4:28:22 PM by Hibernate Tools 4.3.1



/**
 * Pelanggan generated by hbm2java
 */
public class Pelanggan  implements java.io.Serializable {


     private String nipe;
     private String nama;
     private String alamat;
     private String jenkel;
     private String tgllahir;
     private String agama;
     private String telp;

    public Pelanggan() {
    }

	
    public Pelanggan(String nipe) {
        this.nipe = nipe;
    }
    public Pelanggan(String nipe, String nama, String alamat, String jenkel, String tgllahir, String agama, String telp) {
       this.nipe = nipe;
       this.nama = nama;
       this.alamat = alamat;
       this.jenkel = jenkel;
       this.tgllahir = tgllahir;
       this.agama = agama;
       this.telp = telp;
    }
   
    public String getNipe() {
        return this.nipe;
    }
    
    public void setNipe(String nipe) {
        this.nipe = nipe;
    }
    public String getNama() {
        return this.nama;
    }
    
    public void setNama(String nama) {
        this.nama = nama;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public String getJenkel() {
        return this.jenkel;
    }
    
    public void setJenkel(String jenkel) {
        this.jenkel = jenkel;
    }
    public String getTgllahir() {
        return this.tgllahir;
    }
    
    public void setTgllahir(String tgllahir) {
        this.tgllahir = tgllahir;
    }
    public String getAgama() {
        return this.agama;
    }
    
    public void setAgama(String agama) {
        this.agama = agama;
    }
    public String getTelp() {
        return this.telp;
    }
    
    public void setTelp(String telp) {
        this.telp = telp;
    }




}


